@startuml

interface PhoneBooth {
  + getBoothNumber(): String
  + isOccupied(): boolean
  + occupy(phoneNumber: String): void
  + release(): void
  + getPhoneNumber(): String
  + insertCoin(coin: Coin): void
  + makeCall(callDuration: int): void
  + endCall(): void
}

class PublicPhoneBooth implements PhoneBooth {
  - String boothNumber
  - boolean isOccupied
  - String phoneNumber
  - List<Coin> insertedCoins
  - int callDuration
  + PublicPhoneBooth(boothNumber: String)
  + getBoothNumber(): String
  + isOccupied(): boolean
  + occupy(phoneNumber: String): void
  + release(): void
  + getPhoneNumber(): String
  + insertCoin(coin: Coin): void
  + makeCall(callDuration: int): void
  + endCall(): void
}

interface Coin {
  + getValue(): int
}

class EuroCoin implements Coin {
  - int value
  + EuroCoin(value: int)
  + getValue(): int
}

interface Call {
  + getCallerPhoneNumber(): String
  + getReceiverPhoneNumber(): String
  + getDuration(): int
}

class PublicCall implements Call {
  - String callerPhoneNumber
  - String receiverPhoneNumber
  - int duration
  + PublicCall(callerPhoneNumber: String, receiverPhoneNumber: String)
  + getCallerPhoneNumber(): String
  + getReceiverPhoneNumber(): String
  + getDuration(): int
}

PhoneBooth <|.. PublicPhoneBooth
PublicPhoneBooth "1" *-- "1..*" Coin
Call <|.. PublicCall

@enduml
