@startuml

interface EatingBehavior{
    +feed():void
}

class feedHerbivore implements EatingBehavior{
    +feed():void
}
class feedOmnivore implements EatingBehavior{
    +feed():void
}
class feedCarnivore implements EatingBehavior{
    +feed():void
}

abstract class Animal{
    -String:name
    -EatingBehavior : eatingBehavior
    +Animal(name:String)
    +setEatingBehavior():void
    +performFeed():void
    +getName():String
}

class Leopard extends Animal{}
class Elephant extends Animal{}
class Monkey extends Animal{}
class Flamingo extends Animal{}


class Zookeeper {
  - List<Animal> animals
  + addAnimal(animal: Animal): void
  + removeAnimal(animal: Animal): void
  + feedAnimals(): void
}

EatingBehavior ..* Animal







@enduml
