@startuml

class University {
  - String name
  - List<Department> departments
  + University(name: String)
  + getName(): String
  + addDepartment(department: Department): void
  + getDepartments(): List<Department>
}

class Department {
  - String name
  - List<Faculty> faculties
  - List<Student> students
  + Department(name: String)
  + getName(): String
  + addFaculty(faculty: Faculty): void
  + getFaculties(): List<Faculty>
  + addStudent(student: Student): void
  + getStudents(): List<Student>
}

class Faculty {
  - String name
  - int credits
  + Faculty(name: String, credits: int)
  + getName(): String
  + getCredits(): int
}

class Student {
  - String name
  - int id
  - List<Faculty> enrolledFaculties
  + Student(name: String, id: int)
  + getName(): String
  + getID(): int
  + enroll(faculty: Faculty): void
  + getEnrolledFaculties(): List<Faculty>
}

University "1" *-- "*" Department
Department "1" *-- "*" Faculty
Department "1" *-- "*" Student

@enduml
